services:
  mongodb:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
